version: '3.8'

services:
    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ~/public_html:/usr/share/nginx/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ~/public_html:/usr/share/nginx/html
        ports:
            - 9000:9000
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
