version: '3.8'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./site-data:/usr/share/nginx/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./site-data:/usr/share/nginx/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
